---
language: ruby
cache: bundler

addons:
  chrome: stable

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

before_install: gem install bundler -v 2.1.2
