---
language: ruby
cache: bundler
sudo: false

addons:
  chrome: stable

before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - nvm install 12

  # TODO: There _must_ be a better way to do this.
  - CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
  - CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
  - curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

notifications:
  email: false