---
language: ruby
cache: bundler
sudo: false

addons:
  chrome: stable

before_install:
  - gem update --system --no-doc
  - gem install bundler --no-doc
  - nvm install 12

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

gemfile:
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_6_0.gemfile
  - gemfiles/rails_master.gemfile

notifications:
  email: false